version: '3.7'

services:
  postgres14:
    container_name: sherpa.postgres
    image: postgres:14-alpine
    ports:
      - 5452:5432
    volumes:
      - postgres14:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root

  sherpa:
    container_name: sherpa
    build:
      context: .
      args:
        ENV: local
    command: 'runserver.sh'
    ports:
      - "8086:8000"
    env_file:
      - .env
    depends_on:
      - postgres14
    volumes:
      - "./src/:/app"

volumes:
  postgres14:
